# Generated by Django 4.1 on 2023-12-13 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level_education', models.CharField(max_length=255)),
                ('last_company', models.CharField(max_length=255)),
                ('year_of_experience', models.PositiveIntegerField()),
                ('desired_job', models.CharField(max_length=255)),
                ('desired_location', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
