# Generated by Django 4.1 on 2023-12-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CvNLP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
