# Generated by Django 4.1 on 2023-12-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CvNLP', '0003_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_csvs/')),
            ],
        ),
    ]
